#####
name: CycleGan
bidirect: True #Unidirectional or bidirectional
regist: False    # With or without registration network

noise_level: 1  #  noise level
port: 6019   #  port parameters
save_root: './output/DSD_U/'
image_save: './output/DSD_U/img/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 80
Corr_lamda: 0
Smooth_lamda: 0
distillation: 5

epoch_to_test: 300
epoch: 0        # Starting epoch,0 means new training
n_epochs: 300     # Ending epoch
batchSize: 1               # size of the batches
dataroot: './data/DSD_U/train'     # root directory of the dataset
val_dataroot: './data/DSD_U/val'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 4         
output_nc: 3                  
cuda: True                
n_cpu: 12


use_iedf: True
half_cycle: True

unaligned: True
teacher_model_location: './Model/colorization/DSD_U_colorization.pth'